// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webapi/webapi.proto

/*
Package webapi is a generated protocol buffer package.

It is generated from these files:
	webapi/webapi.proto

It has these top-level messages:
	HelloRequest
	HelloReply
	GetPictureListReq
	GetPictureListResp
	Picture
*/
package webapi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type HelloReply struct {
	// common.Result result = 1;
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type GetPictureListReq struct {
	Page  int32 `protobuf:"varint,1,opt,name=page" json:"page,omitempty"`
	Limit int32 `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
}

func (m *GetPictureListReq) Reset()                    { *m = GetPictureListReq{} }
func (m *GetPictureListReq) String() string            { return proto.CompactTextString(m) }
func (*GetPictureListReq) ProtoMessage()               {}
func (*GetPictureListReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetPictureListReq) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetPictureListReq) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetPictureListResp struct {
	StatusCode int32      `protobuf:"varint,1,opt,name=statusCode" json:"statusCode,omitempty"`
	Data       []*Picture `protobuf:"bytes,2,rep,name=data" json:"data,omitempty"`
	ErrMsg     string     `protobuf:"bytes,3,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *GetPictureListResp) Reset()                    { *m = GetPictureListResp{} }
func (m *GetPictureListResp) String() string            { return proto.CompactTextString(m) }
func (*GetPictureListResp) ProtoMessage()               {}
func (*GetPictureListResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetPictureListResp) GetStatusCode() int32 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *GetPictureListResp) GetData() []*Picture {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetPictureListResp) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type Picture struct {
	Id     string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Title  string `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	Name   string `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ImgNum int32  `protobuf:"varint,4,opt,name=imgNum" json:"imgNum,omitempty"`
	ImgSrc string `protobuf:"bytes,5,opt,name=imgSrc" json:"imgSrc,omitempty"`
}

func (m *Picture) Reset()                    { *m = Picture{} }
func (m *Picture) String() string            { return proto.CompactTextString(m) }
func (*Picture) ProtoMessage()               {}
func (*Picture) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Picture) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Picture) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Picture) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Picture) GetImgNum() int32 {
	if m != nil {
		return m.ImgNum
	}
	return 0
}

func (m *Picture) GetImgSrc() string {
	if m != nil {
		return m.ImgSrc
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "webapi.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "webapi.HelloReply")
	proto.RegisterType((*GetPictureListReq)(nil), "webapi.GetPictureListReq")
	proto.RegisterType((*GetPictureListResp)(nil), "webapi.GetPictureListResp")
	proto.RegisterType((*Picture)(nil), "webapi.Picture")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hello service

type HelloClient interface {
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	GetPictureList(ctx context.Context, in *GetPictureListReq, opts ...grpc.CallOption) (*GetPictureListResp, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/webapi.Hello/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) GetPictureList(ctx context.Context, in *GetPictureListReq, opts ...grpc.CallOption) (*GetPictureListResp, error) {
	out := new(GetPictureListResp)
	err := grpc.Invoke(ctx, "/webapi.Hello/GetPictureList", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service

type HelloServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	GetPictureList(context.Context, *GetPictureListReq) (*GetPictureListResp, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webapi.Hello/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_GetPictureList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPictureListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).GetPictureList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/webapi.Hello/GetPictureList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).GetPictureList(ctx, req.(*GetPictureListReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "webapi.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Hello_SayHello_Handler,
		},
		{
			MethodName: "GetPictureList",
			Handler:    _Hello_GetPictureList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "webapi/webapi.proto",
}

func init() { proto.RegisterFile("webapi/webapi.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 308 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xa5, 0xf9, 0xd7, 0xdf, 0x6f, 0x94, 0x8a, 0x63, 0x91, 0x35, 0x07, 0x29, 0x2b, 0x48, 0x4f,
	0x15, 0xaa, 0x57, 0x4f, 0x1e, 0xea, 0x41, 0x45, 0xb6, 0x9f, 0x60, 0xdb, 0x2c, 0x61, 0x21, 0x31,
	0x9b, 0xec, 0x06, 0xe9, 0x17, 0xf0, 0x73, 0xcb, 0xfe, 0x89, 0xd6, 0x8a, 0xa7, 0xcc, 0x9b, 0x79,
	0x79, 0x79, 0xf3, 0x26, 0x70, 0xf6, 0x2e, 0x36, 0x5c, 0xc9, 0x1b, 0xff, 0x58, 0xa8, 0xae, 0x31,
	0x0d, 0x66, 0x1e, 0x51, 0x0a, 0xc7, 0x8f, 0xa2, 0xaa, 0x1a, 0x26, 0xda, 0x5e, 0x68, 0x83, 0x08,
	0xc9, 0x1b, 0xaf, 0x05, 0x19, 0xcd, 0x46, 0xf3, 0xff, 0xcc, 0xd5, 0xf4, 0x1a, 0x20, 0x70, 0x54,
	0xb5, 0x43, 0x02, 0xe3, 0x5a, 0x68, 0xcd, 0x4b, 0x41, 0x22, 0x47, 0x1a, 0x20, 0xbd, 0x87, 0xd3,
	0x95, 0x30, 0xaf, 0x72, 0x6b, 0xfa, 0x4e, 0x3c, 0x49, 0x6d, 0x98, 0x68, 0xad, 0xa0, 0xb2, 0x5c,
	0x2b, 0x98, 0x32, 0x57, 0xe3, 0x14, 0xd2, 0x4a, 0xd6, 0xd2, 0x38, 0x81, 0x94, 0x79, 0x40, 0x5b,
	0xc0, 0xc3, 0xd7, 0xb5, 0xc2, 0x4b, 0x00, 0x6d, 0xb8, 0xe9, 0xf5, 0x43, 0x53, 0x0c, 0x2a, 0x7b,
	0x1d, 0xbc, 0x82, 0xa4, 0xe0, 0x86, 0x93, 0x68, 0x16, 0xcf, 0x8f, 0x96, 0x27, 0x8b, 0xb0, 0x65,
	0x90, 0x61, 0x6e, 0x88, 0xe7, 0x90, 0x89, 0xae, 0x7b, 0xd6, 0x25, 0x89, 0x9d, 0xe5, 0x80, 0xa8,
	0x86, 0x71, 0x20, 0xe2, 0x04, 0x22, 0x59, 0x84, 0xb5, 0x23, 0x59, 0x58, 0x8f, 0x46, 0x9a, 0x6a,
	0x58, 0xd2, 0x83, 0xaf, 0x78, 0xe2, 0xef, 0x78, 0xac, 0xb8, 0xac, 0xcb, 0x97, 0xbe, 0x26, 0x89,
	0x73, 0x17, 0x50, 0xe8, 0xaf, 0xbb, 0x2d, 0x49, 0xfd, 0x47, 0x3d, 0x5a, 0x7e, 0x8c, 0x20, 0x75,
	0x79, 0xe2, 0x1d, 0xfc, 0x5b, 0xf3, 0x9d, 0xaf, 0xa7, 0x83, 0xf3, 0xfd, 0x73, 0xe4, 0x78, 0xd0,
	0xb5, 0x07, 0x58, 0xc1, 0xe4, 0x67, 0x4e, 0x78, 0x31, 0xb0, 0x7e, 0xc5, 0x9f, 0xe7, 0x7f, 0x8d,
	0xb4, 0xda, 0x64, 0xee, 0x57, 0xb8, 0xfd, 0x0c, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xe1, 0xcc, 0xcb,
	0x21, 0x02, 0x00, 0x00,
}
